# Generated by Django 2.2.1 on 2019-07-14 20:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=15, unique=True)),
                ('document_type', models.CharField(choices=[('c.i.', 'C.I.'), ('r.i.f.', 'R.I.F.')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, region=None, unique=True, verbose_name='mobile')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, null=True, region=None, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyTypePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('supply_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SupplyType')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=59, unique=True)),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Person')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=59)),
                ('account_type', models.CharField(choices=[('ahorro', 'AHORRO'), ('corriente', 'CORRIENTE')], max_length=9)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('document_code', models.CharField(max_length=15)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BankAccount', related_query_name='BankAccount', to='profiles.Provider')),
            ],
        ),
    ]
