# Generated by Django 2.2.1 on 2019-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(max_length=59, unique=True),
        ),
    ]
