# Generated by Django 2.2.1 on 2019-06-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', related_query_name='receipts', to='profiles.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('tapas', 'TAPAS'), ('envases', 'ENVASES')], max_length=7)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', related_query_name='receipts', to='activities.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField(null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', related_query_name='interview', to='profiles.Person')),
            ],
        ),
    ]
