# Generated by Django 2.2.1 on 2019-06-10 19:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=15, unique=True)),
                ('document_type', models.CharField(choices=[('c.i.', 'C.I.'), ('r.i.f.', 'R.I.F.')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, region=None, unique=True, verbose_name='mobile')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, null=True, region=None, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField(null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', related_query_name='interview', to='interviews.Person')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', related_query_name='cities', to='interviews.State')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('reference', models.TextField(null=True)),
                ('details', models.TextField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='addresses', to='interviews.City')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', related_query_name='address', to='interviews.Person')),
            ],
        ),
    ]
