# Generated by Django 2.2.1 on 2019-05-30 02:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=15, unique=True)),
                ('document_type', models.CharField(choices=[('c.i.', 'C.I.'), ('r.i.f.', 'R.I.F.')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, region=None, unique=True, verbose_name='mobile')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, null=True, region=None, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
