# Generated by Django 2.2.1 on 2019-06-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=30)),
                ('reference', models.TextField(null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
