# Generated by Django 2.2.1 on 2019-06-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=59)),
                ('account_type', models.CharField(choices=[('ahorro', 'AHORRO'), ('corriente', 'CORRIENTE')], max_length=9)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('document_code', models.CharField(max_length=15)),
            ],
        ),
    ]
