# Generated by Django 2.2.1 on 2019-06-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', related_query_name='receipts', to='recipiency.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('tapas', 'TAPAS'), ('envases', 'ENVASES')], max_length=7)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', related_query_name='receipts', to='recipiency.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=59)),
                ('account_type', models.CharField(choices=[('ahorro', 'AHORRO'), ('corriente', 'CORRIENTE')], max_length=9)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('document_code', models.CharField(max_length=15)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BankAccount', related_query_name='BankAccount', to='recipiency.Provider')),
            ],
        ),
    ]
